spring:
  datasource:
    url: jdbc:h2:mem:bizweaver_db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      firstName: Admin
    metrics:
      enabled: true
    filter:
      create: All tasks