spring:
  datasource:
    url: jdbc:h2:mem:bizweaver_db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    metrics:
      enabled: true
    filter:
      create: All tasks